export const CategoryImage: { [key: string]: string } = {
  인프런: "/roadmapRef/inflearnLogo.svg",
  유튜브: "/roadmapRef/youtubeLogo.svg",
  유데미: "/roadmapRef/udemyLogo.svg",
  코딩애플: "/roadmapRef/codingappleLogo.svg",
  노마드코더: "/roadmapRef/nomadcodersLogo.svg",
  video: "/roadmapRef/video.png",
  book: "/roadmapRef/book.svg",
  도서: "/roadmapRef/book.svg",
  posting: "/roadmapRef/posting.svg",
  개인블로그: "/roadmapRef/posting.svg",
  기업블로그: "/roadmapRef/posting.svg",
  공식문서한글화: "/roadmapRef/posting.svg",
  공식문서: "/roadmapRef/posting.svg",
  위키독스: "/roadmapRef/posting.svg",
  패스트캠퍼스: "/roadmapRef/fastcampusLogo.png",
  깃허브: "/roadmapRef/githubLogo.svg",
  부스트코스: "/roadmapRef/boostcourseLogo.png",
  MDN문서: "/roadmapRef/mdnLogo.svg",
  코드아카데미: "/roadmapRef/codeacademyLogo.svg",
  프로그래머스: "/roadmapRef/programmersLogo.JPG",
  오픈소스: "/roadmapRef/opensourceLogo.png",
  드림코딩: "/roadmapRef/dreamcodingLogo.svg",
};
