import { Header } from '../components/Header';
import { SideBar } from '../components/SideBar';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <SideBar />
        <div className="flex flex-col items-center justify-between min-h-screen p-24 ml-72 ">
          {children}
        </div>
      </body>
    </html>
  );
}
