import { RoadData } from '@/roadmap_json/roadmap_data';

export const code_data_private: RoadData = {
  nid: 1001,
  name: 'code',
  description:
    '개발을 하다보면 반복하게 되는 부분이 발생할 때가 있고, 그런 반복되는 부분을 수정해야되는 상황도 생깁니다. 반복되는 내용이 2~3번정도라면 일일이해도 되지만 양이 많아진다면 불필요한 리소스낭비가 되기때문에, 이런 반복되는 부분을 재사용하기 위해 만들어진 것이 바로 \'코드섹션\'입니다. 코드를 잘 작성하고 잘 관리하면, 개발자의 생산성을 높일 수 있습니다. 코드를 잘 작성하기 위해서는, 코드의 가독성, 유지보수성, 재사용성, 확장성, 테스트 용이성 등을 고려해야합니다. 이러한 코드의 품질을 높이기 위해, 코드를 작성할 때는 코드 컨벤션을 지키고, 코드 리뷰를 통해 피드백을 받아야합니다. 또한, 코드를 작성할 때는, SOLID 원칙을 지키고, 디자인 패턴을 적용해야합니다. 이러한 코드의 품질을 높이는 것은 개발자의 역량을 높이는 것과도 연관이 있습니다. 따라서, 코드의 품질을 높이기 위해, 코드 컨벤션, 코드 리뷰, SOLID 원칙, 디자인 패턴 등을 공부하고, 실제로 적용해보는 것이 중요합니다.',
  ref: [
    {
      uuid: '1001',
      title: '디자인패턴 스터디',
      url: 'https://younggeun0.github.io/%EB%94%94%EC%9E%90%EC%9D%B8%ED%8C%A8%ED%84%B4-%EC%8A%A4%ED%84%B0%EB%94%94/',
      grade: 3,
      amount: '',
      price: 0,
      category: '깃허브',
    },
    {
      uuid: '1002',
      title: '자바로 된 디자인 패턴',
      url: 'https://refactoring.guru/ko/design-patterns/java',
      grade: 3,
      amount: '',
      price: 0,
      category: '개인블로그',
    },
    {
      uuid: '1003',
      title: '코딩으로 학습하는 GoF의 디자인 패턴',
      url: 'https://www.inflearn.com/course/%EB%94%94%EC%9E%90%EC%9D%B8-%ED%8C%A8%ED%84%B4',
      grade: 3,
      amount: '총 11시간37분',
      price: 88000,
      category: '인프런',
    },
    {
      uuid: '1004',
      title: '클린 코드',
      url: 'https://www.yes24.com/Product/Goods/11681152',
      grade: 4,
      amount: '총 584쪽',
      price: 33000,
      category: '도서',
    },
    {
      uuid: '1005',
      title: '클린 아키텍처',
      url: 'https://www.yes24.com/Product/Goods/77283734',
      grade: 4,
      amount: '총 432쪽',
      price: 29000,
      category: '도서',
    },
    {
      uuid: '1006',
      title: '헤드 퍼스트 디자인 패턴',
      url: 'https://product.kyobobook.co.kr/detail/S000001810483',
      grade: 2,
      amount: '총 656쪽',
      price: 36000,
      category: '도서',
    },
    {
      uuid: '1007',
      title: '개발자가 반드시 정복해야 할 객체 지향과 디자인 패턴',
      url: 'https://www.yes24.com/Product/Goods/9179120',
      grade: 3,
      amount: '총 264쪽',
      price: 20000,
      category: '도서',
    },
    {
      uuid: '1008',
      title: '객체지향의 사실과 오해',
      url: 'https://product.kyobobook.co.kr/detail/S000001628109',
      grade: 2,
      amount: '총 260쪽',
      price: 20000,
      category: '도서',
    },
    {
      uuid: '1009',
      title: '오브젝트/코드로 이해하는 객체지향 설계',
      url: 'https://www.yes24.com/Product/Goods/74219491',
      grade: 4,
      amount: '총 656쪽',
      price: 38000,
      category: '도서',
    },
  ],
  children: [],
};