import { RoadData } from '@/roadmap_json/roadmap_data';
import { personal_springJPA_data_private } from '@/roadmap_json/roadmap/backend_data_1/spring_2/JPA_3/personal_data';

export const spring_JPA_data_private: RoadData = {
  nid: 124,
  depth: 2,
  name: 'Spring JPA',
  description:
    'DB와 연결하여 데이터를 읽고 쓰기 위해서 SQL쿼리문을 알아야하지만, JPA을 사용하면 객체중심으로 애플리케이션 개발이 가능하여 생산성을 높여줄 수 있어 많은 개발자들이 사용하고 있습니다.',
  // url: 'https://docs.spring.io/spring-data/jpa/docs/current/reference/html/',
  ref: [
    {
      uuid: '124000',
      title:
        '자바 ORM 표준 JPA 프로그래밍 - 기본편',
      url: 'https://www.inflearn.com/course/ORM-JPA-Basic',
      grade: 1,
      amount: '총 16시간 3분',
      price: 121000,
      category: '인프런',
    },
    {
      uuid: '124001',
      title: '실전! 스프링 부트와 JPA 활용1 - 웹 애플리케이션 개발',
      url: 'https://inf.run/CP5C',
      grade: 1,
      amount: '총 7시간 44분',
      price: 88000,
      category: '인프런',
    },
    {
      uuid: '124002',
      title: '실전! 스프링 부트와 JPA 활용2 - API 개발과 성능 최적화',
      url: 'https://inf.run/5qSG',
      grade: 2,
      amount: '총 6시간 35분',
      price: 88000,
      category: '인프런',
    },
    {
      uuid: '124003',
      title: '실전! 스프링 데이터 JPA',
      url: 'https://inf.run/SXfL',
      grade: 3,
      amount: '총 7시간 17분',
      price: 88000,
      category: '인프런',
    },
    {
      uuid: '124004',
      title: '실전! Querydsl',
      url: 'https://inf.run/PUCe',
      grade: 4,
      amount: '총 6시간 24분',
      price: 88000,
      category: '인프런',
    },
    {
      uuid: '124005',
      title: '나무 소리 JPA for Beginner',
      url: 'https://youtube.com/playlist?list=PLOSNUO27qFbvzGd3yWbHISxHctPRKkctO',
      grade: 2,
      amount: '총 4시간 52분',
      price: 38000,
      category: '유튜브',
    },
    {
      uuid: '124006',
      title: '자바 ORM 표준 JPA 프로그래밍',
      url: 'https://product.kyobobook.co.kr/detail/S000000935744',
      grade: 3,
      amount: '총  734쪽',
      price: 43000,
      category: '도서',
    },
    {
      uuid: '124007',
      title: 'JPA 퀵스타트',
      url: 'https://product.kyobobook.co.kr/detail/S000001891098',
      grade: 3,
      amount: '총 708쪽',
      price: 30000,
      category: '도서',
    },
    {
      uuid: '124008',
      title:
        '스프링 데이터 JPA 레퍼런스 번역 Version 1.8.1.RELEASE',
      url: 'https://arahansa.github.io/docs_spring/jpa.html',
      grade: 3,
      amount: '',
      price: 0,
      category: '오픈소스',
    },
    {
      uuid: '124009',
      title: 'Spring Data JPA - Reference Documentation',
      url: 'https://docs.spring.io/spring-data/jpa/docs/current/reference/html/',
      grade: 4,
      amount: '',
      price: 0,
      category: '오픈소스',
    },
  ],
  children: [personal_springJPA_data_private],
};
